- hosts: 192.168.1.4
  tasks:
   - name: Install apache2
     apt: pkg=apache2 state=installed update_cache=true
     notify:
      - Start apache2

  handlers:
   - name: Start apache2
     service: name=apache2 state=started
